# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/home.ui',
# licensing of 'ui/home.ui' applies.
#
# Created: Mon May 18 13:53:01 2020
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(1060, 703)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(197, 191))
        self.frame_3.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.csMeasurementsLabel = QtWidgets.QLabel(self.frame_3)
        self.csMeasurementsLabel.setObjectName("csMeasurementsLabel")
        self.verticalLayout.addWidget(self.csMeasurementsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.csMeasurementsPathLine = QtWidgets.QLineEdit(self.frame_3)
        self.csMeasurementsPathLine.setObjectName("csMeasurementsPathLine")
        self.horizontalLayout.addWidget(self.csMeasurementsPathLine)
        self.csMeasurementsButton = QtWidgets.QToolButton(self.frame_3)
        self.csMeasurementsButton.setObjectName("csMeasurementsButton")
        self.horizontalLayout.addWidget(self.csMeasurementsButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.samplingMatrixLabel = QtWidgets.QLabel(self.frame_3)
        self.samplingMatrixLabel.setObjectName("samplingMatrixLabel")
        self.verticalLayout_2.addWidget(self.samplingMatrixLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.samplingMatrixPathLine = QtWidgets.QLineEdit(self.frame_3)
        self.samplingMatrixPathLine.setObjectName("samplingMatrixPathLine")
        self.horizontalLayout_2.addWidget(self.samplingMatrixPathLine)
        self.samplingMatrixButton = QtWidgets.QToolButton(self.frame_3)
        self.samplingMatrixButton.setObjectName("samplingMatrixButton")
        self.horizontalLayout_2.addWidget(self.samplingMatrixButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.initializationMatrixLabel = QtWidgets.QLabel(self.frame_3)
        self.initializationMatrixLabel.setObjectName("initializationMatrixLabel")
        self.verticalLayout_3.addWidget(self.initializationMatrixLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.initializationMatrixPathLine = QtWidgets.QLineEdit(self.frame_3)
        self.initializationMatrixPathLine.setObjectName("initializationMatrixPathLine")
        self.horizontalLayout_3.addWidget(self.initializationMatrixPathLine)
        self.initializationMatrixButton = QtWidgets.QToolButton(self.frame_3)
        self.initializationMatrixButton.setObjectName("initializationMatrixButton")
        self.horizontalLayout_3.addWidget(self.initializationMatrixButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.csRatioLabel = QtWidgets.QLabel(self.frame_3)
        self.csRatioLabel.setObjectName("csRatioLabel")
        self.horizontalLayout_4.addWidget(self.csRatioLabel)
        self.csRatiosComboBox = QtWidgets.QComboBox(self.frame_3)
        self.csRatiosComboBox.setObjectName("csRatiosComboBox")
        self.csRatiosComboBox.addItem("")
        self.csRatiosComboBox.addItem("")
        self.csRatiosComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.csRatiosComboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.reconstructButton = QtWidgets.QPushButton(self.frame_3)
        self.reconstructButton.setObjectName("reconstructButton")
        self.gridLayout_2.addWidget(self.reconstructButton, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(197, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.recoveredImageLabel = QtWidgets.QLabel(self.frame)
        self.recoveredImageLabel.setObjectName("recoveredImageLabel")
        self.gridLayout_4.addWidget(self.recoveredImageLabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(220, 150))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_4.addWidget(self.saveButton, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 1)
        HomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 39))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        HomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)
        self.actionHome = QtWidgets.QAction(HomeWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionIntructions = QtWidgets.QAction(HomeWindow)
        self.actionIntructions.setObjectName("actionIntructions")
        self.actionSettings = QtWidgets.QAction(HomeWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuMenu.addAction(self.actionHome)
        self.menuMenu.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionIntructions)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        HomeWindow.setWindowTitle(QtWidgets.QApplication.translate("HomeWindow", "NetMD", None, -1))
        self.csMeasurementsLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "CS Measurements", None, -1))
        self.csMeasurementsButton.setText(QtWidgets.QApplication.translate("HomeWindow", "...", None, -1))
        self.samplingMatrixLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Sampling Matrix", None, -1))
        self.samplingMatrixButton.setText(QtWidgets.QApplication.translate("HomeWindow", "...", None, -1))
        self.initializationMatrixLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Initialization Matrix", None, -1))
        self.initializationMatrixButton.setText(QtWidgets.QApplication.translate("HomeWindow", "...", None, -1))
        self.csRatioLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "CS Ratio", None, -1))
        self.csRatiosComboBox.setItemText(0, QtWidgets.QApplication.translate("HomeWindow", "10%", None, -1))
        self.csRatiosComboBox.setItemText(1, QtWidgets.QApplication.translate("HomeWindow", "25%", None, -1))
        self.csRatiosComboBox.setItemText(2, QtWidgets.QApplication.translate("HomeWindow", "50%", None, -1))
        self.reconstructButton.setText(QtWidgets.QApplication.translate("HomeWindow", "Reconstruct", None, -1))
        self.recoveredImageLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "                          Recovered Image", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("HomeWindow", "Placeholder", None, -1))
        self.saveButton.setText(QtWidgets.QApplication.translate("HomeWindow", "Save", None, -1))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("HomeWindow", "Menu", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("HomeWindow", "Help", None, -1))
        self.actionHome.setText(QtWidgets.QApplication.translate("HomeWindow", "Home", None, -1))
        self.actionIntructions.setText(QtWidgets.QApplication.translate("HomeWindow", "Intructions", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("HomeWindow", "Settings", None, -1))

