# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/home_v2.ui',
# licensing of 'ui/home_v2.ui' applies.
#
# Created: Wed May 27 15:05:55 2020
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(1300, 820)
        HomeWindow.setMinimumSize(QtCore.QSize(1300, 820))
        HomeWindow.setMaximumSize(QtCore.QSize(1300, 820))
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(1050, 650))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(256, 300))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_4.addWidget(self.saveButton, 4, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.origImageLabel = QtWidgets.QLabel(self.frame)
        self.origImageLabel.setObjectName("origImageLabel")
        self.verticalLayout_6.addWidget(self.origImageLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.origImagePathLine = QtWidgets.QLineEdit(self.frame)
        self.origImagePathLine.setObjectName("origImagePathLine")
        self.horizontalLayout_6.addWidget(self.origImagePathLine)
        self.origImageButton = QtWidgets.QToolButton(self.frame)
        self.origImageButton.setObjectName("origImageButton")
        self.horizontalLayout_6.addWidget(self.origImageButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        self.recoveredImageLabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recoveredImageLabel.sizePolicy().hasHeightForWidth())
        self.recoveredImageLabel.setSizePolicy(sizePolicy)
        self.recoveredImageLabel.setMinimumSize(QtCore.QSize(256, 256))
        self.recoveredImageLabel.setText("")
        self.recoveredImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recoveredImageLabel.setObjectName("recoveredImageLabel")
        self.gridLayout_4.addWidget(self.recoveredImageLabel, 1, 0, 1, 1)
        self.reconstructedImageLabel = QtWidgets.QLabel(self.frame)
        self.reconstructedImageLabel.setObjectName("reconstructedImageLabel")
        self.gridLayout_4.addWidget(self.reconstructedImageLabel, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.snrLabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snrLabel.sizePolicy().hasHeightForWidth())
        self.snrLabel.setSizePolicy(sizePolicy)
        self.snrLabel.setMinimumSize(QtCore.QSize(256, 0))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.snrLabel.setFont(font)
        self.snrLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.snrLabel.setLineWidth(0)
        self.snrLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.snrLabel.setObjectName("snrLabel")
        self.verticalLayout_7.addWidget(self.snrLabel)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.snrButton = QtWidgets.QPushButton(self.frame)
        self.snrButton.setObjectName("snrButton")
        self.horizontalLayout_8.addWidget(self.snrButton)
        self.snrLCDNumber = QtWidgets.QLCDNumber(self.frame)
        self.snrLCDNumber.setSmallDecimalPoint(True)
        self.snrLCDNumber.setDigitCount(8)
        self.snrLCDNumber.setProperty("value", 0.0)
        self.snrLCDNumber.setObjectName("snrLCDNumber")
        self.horizontalLayout_8.addWidget(self.snrLCDNumber)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 191))
        self.frame_3.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.reconstructButton = QtWidgets.QPushButton(self.frame_3)
        self.reconstructButton.setObjectName("reconstructButton")
        self.gridLayout_2.addWidget(self.reconstructButton, 2, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.csMeasurementsLabel = QtWidgets.QLabel(self.frame_3)
        self.csMeasurementsLabel.setObjectName("csMeasurementsLabel")
        self.verticalLayout.addWidget(self.csMeasurementsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.csMeasurementsPathLine = QtWidgets.QLineEdit(self.frame_3)
        self.csMeasurementsPathLine.setMinimumSize(QtCore.QSize(0, 30))
        self.csMeasurementsPathLine.setObjectName("csMeasurementsPathLine")
        self.horizontalLayout.addWidget(self.csMeasurementsPathLine)
        self.csMeasurementsButton = QtWidgets.QToolButton(self.frame_3)
        self.csMeasurementsButton.setObjectName("csMeasurementsButton")
        self.horizontalLayout.addWidget(self.csMeasurementsButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.samplingMatrixLabel = QtWidgets.QLabel(self.frame_3)
        self.samplingMatrixLabel.setObjectName("samplingMatrixLabel")
        self.verticalLayout_2.addWidget(self.samplingMatrixLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.samplingMatrixPathLine = QtWidgets.QLineEdit(self.frame_3)
        self.samplingMatrixPathLine.setMinimumSize(QtCore.QSize(0, 30))
        self.samplingMatrixPathLine.setObjectName("samplingMatrixPathLine")
        self.horizontalLayout_2.addWidget(self.samplingMatrixPathLine)
        self.samplingMatrixButton = QtWidgets.QToolButton(self.frame_3)
        self.samplingMatrixButton.setObjectName("samplingMatrixButton")
        self.horizontalLayout_2.addWidget(self.samplingMatrixButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.initializationMatrixLabel = QtWidgets.QLabel(self.frame_3)
        self.initializationMatrixLabel.setObjectName("initializationMatrixLabel")
        self.verticalLayout_3.addWidget(self.initializationMatrixLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.initializationMatrixPathLine = QtWidgets.QLineEdit(self.frame_3)
        self.initializationMatrixPathLine.setMinimumSize(QtCore.QSize(0, 30))
        self.initializationMatrixPathLine.setObjectName("initializationMatrixPathLine")
        self.horizontalLayout_3.addWidget(self.initializationMatrixPathLine)
        self.initializationMatrixButton = QtWidgets.QToolButton(self.frame_3)
        self.initializationMatrixButton.setObjectName("initializationMatrixButton")
        self.horizontalLayout_3.addWidget(self.initializationMatrixButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.csRatioLabel = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csRatioLabel.sizePolicy().hasHeightForWidth())
        self.csRatioLabel.setSizePolicy(sizePolicy)
        self.csRatioLabel.setMinimumSize(QtCore.QSize(0, 34))
        self.csRatioLabel.setObjectName("csRatioLabel")
        self.horizontalLayout_4.addWidget(self.csRatioLabel)
        self.csRatiosComboBox = QtWidgets.QComboBox(self.frame_3)
        self.csRatiosComboBox.setEditable(False)
        self.csRatiosComboBox.setMaxVisibleItems(10)
        self.csRatiosComboBox.setObjectName("csRatiosComboBox")
        self.csRatiosComboBox.addItem("")
        self.csRatiosComboBox.addItem("")
        self.csRatiosComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.csRatiosComboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widthLabel = QtWidgets.QLabel(self.frame_3)
        self.widthLabel.setObjectName("widthLabel")
        self.horizontalLayout_5.addWidget(self.widthLabel)
        self.widthLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.horizontalLayout_5.addWidget(self.widthLineEdit)
        self.heightLabel = QtWidgets.QLabel(self.frame_3)
        self.heightLabel.setObjectName("heightLabel")
        self.horizontalLayout_5.addWidget(self.heightLabel)
        self.heightLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.horizontalLayout_5.addWidget(self.heightLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 1)
        HomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 39))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        HomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)
        self.actionHome = QtWidgets.QAction(HomeWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionHome_2 = QtWidgets.QAction(HomeWindow)
        self.actionHome_2.setObjectName("actionHome_2")
        self.actionIntructions = QtWidgets.QAction(HomeWindow)
        self.actionIntructions.setObjectName("actionIntructions")
        self.actionSettings = QtWidgets.QAction(HomeWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionInstructions = QtWidgets.QAction(HomeWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.menuMenu.addAction(self.actionSettings)
        self.menuMenu.addAction(self.actionInstructions)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        HomeWindow.setWindowTitle(QtWidgets.QApplication.translate("HomeWindow", "NetMD", None, -1))
        self.saveButton.setText(QtWidgets.QApplication.translate("HomeWindow", "Save", None, -1))
        self.origImageLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Original Image", None, -1))
        self.origImageButton.setText(QtWidgets.QApplication.translate("HomeWindow", "...", None, -1))
        self.reconstructedImageLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Reconstructed Image", None, -1))
        self.snrLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Signal-to-Noise Ratio (SNR)", None, -1))
        self.snrButton.setText(QtWidgets.QApplication.translate("HomeWindow", "Calculate", None, -1))
        self.reconstructButton.setText(QtWidgets.QApplication.translate("HomeWindow", "Reconstruct", None, -1))
        self.csMeasurementsLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "CS Measurements", None, -1))
        self.csMeasurementsButton.setText(QtWidgets.QApplication.translate("HomeWindow", "...", None, -1))
        self.samplingMatrixLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Sampling Matrix", None, -1))
        self.samplingMatrixButton.setText(QtWidgets.QApplication.translate("HomeWindow", "...", None, -1))
        self.initializationMatrixLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Initialization Matrix", None, -1))
        self.initializationMatrixButton.setText(QtWidgets.QApplication.translate("HomeWindow", "...", None, -1))
        self.csRatioLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "CS Ratio", None, -1))
        self.csRatiosComboBox.setCurrentText(QtWidgets.QApplication.translate("HomeWindow", "10", None, -1))
        self.csRatiosComboBox.setItemText(0, QtWidgets.QApplication.translate("HomeWindow", "10", None, -1))
        self.csRatiosComboBox.setItemText(1, QtWidgets.QApplication.translate("HomeWindow", "25", None, -1))
        self.csRatiosComboBox.setItemText(2, QtWidgets.QApplication.translate("HomeWindow", "50", None, -1))
        self.widthLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Width", None, -1))
        self.heightLabel.setText(QtWidgets.QApplication.translate("HomeWindow", "Height", None, -1))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("HomeWindow", "Menu", None, -1))
        self.actionHome.setText(QtWidgets.QApplication.translate("HomeWindow", "Program", None, -1))
        self.actionHome_2.setText(QtWidgets.QApplication.translate("HomeWindow", "Home", None, -1))
        self.actionIntructions.setText(QtWidgets.QApplication.translate("HomeWindow", "Intructions", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("HomeWindow", "Settings", None, -1))
        self.actionInstructions.setText(QtWidgets.QApplication.translate("HomeWindow", "Instructions", None, -1))

