# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui',
# licensing of 'ui/settings.ui' applies.
#
# Created: Mon May 18 13:53:21 2020
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(737, 590)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(251, 241))
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.settingsLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.settingsLabel.setFont(font)
        self.settingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.settingsLabel.setObjectName("settingsLabel")
        self.gridLayout.addWidget(self.settingsLabel, 0, 0, 1, 1)
        self.istaLabel = QtWidgets.QLabel(self.frame)
        self.istaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.istaLabel.setObjectName("istaLabel")
        self.gridLayout.addWidget(self.istaLabel, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.istaPathLine = QtWidgets.QLineEdit(self.frame)
        self.istaPathLine.setObjectName("istaPathLine")
        self.horizontalLayout.addWidget(self.istaPathLine)
        self.istaUploadButton = QtWidgets.QToolButton(self.frame)
        self.istaUploadButton.setObjectName("istaUploadButton")
        self.horizontalLayout.addWidget(self.istaUploadButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.rcmddLabel = QtWidgets.QLabel(self.frame)
        self.rcmddLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rcmddLabel.setObjectName("rcmddLabel")
        self.gridLayout.addWidget(self.rcmddLabel, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rcmddPathLine = QtWidgets.QLineEdit(self.frame)
        self.rcmddPathLine.setObjectName("rcmddPathLine")
        self.horizontalLayout_2.addWidget(self.rcmddPathLine)
        self.rcmddUploadButton = QtWidgets.QToolButton(self.frame)
        self.rcmddUploadButton.setObjectName("rcmddUploadButton")
        self.horizontalLayout_2.addWidget(self.rcmddUploadButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 737, 39))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)
        self.actionProgram = QtWidgets.QAction(SettingsWindow)
        self.actionProgram.setObjectName("actionProgram")
        self.actionHome = QtWidgets.QAction(SettingsWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionSettings = QtWidgets.QAction(SettingsWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionInstructions = QtWidgets.QAction(SettingsWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.menuMenu.addAction(self.actionHome)
        self.menuMenu.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionInstructions)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        SettingsWindow.setWindowTitle(QtWidgets.QApplication.translate("SettingsWindow", "Settings", None, -1))
        self.settingsLabel.setText(QtWidgets.QApplication.translate("SettingsWindow", "Settings", None, -1))
        self.istaLabel.setText(QtWidgets.QApplication.translate("SettingsWindow", "ISTA-Net Model", None, -1))
        self.istaUploadButton.setText(QtWidgets.QApplication.translate("SettingsWindow", "...", None, -1))
        self.rcmddLabel.setText(QtWidgets.QApplication.translate("SettingsWindow", "RCMDD Model", None, -1))
        self.rcmddUploadButton.setText(QtWidgets.QApplication.translate("SettingsWindow", "...", None, -1))
        self.saveButton.setText(QtWidgets.QApplication.translate("SettingsWindow", "Save", None, -1))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("SettingsWindow", "Menu", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("SettingsWindow", "Help", None, -1))
        self.actionProgram.setText(QtWidgets.QApplication.translate("SettingsWindow", "Program", None, -1))
        self.actionHome.setText(QtWidgets.QApplication.translate("SettingsWindow", "Home", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("SettingsWindow", "Settings", None, -1))
        self.actionInstructions.setText(QtWidgets.QApplication.translate("SettingsWindow", "Instructions", None, -1))

