# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui',
# licensing of 'ui/settings.ui' applies.
#
# Created: Wed May 27 15:04:48 2020
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(939, 671)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(251, 241))
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.settingsLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.settingsLabel.setFont(font)
        self.settingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.settingsLabel.setObjectName("settingsLabel")
        self.gridLayout.addWidget(self.settingsLabel, 0, 0, 1, 1)
        self.saveSettingsButton = QtWidgets.QPushButton(self.frame)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.gridLayout.addWidget(self.saveSettingsButton, 7, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.istaLabel = QtWidgets.QLabel(self.frame)
        self.istaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.istaLabel.setObjectName("istaLabel")
        self.verticalLayout.addWidget(self.istaLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.istaPathLine = QtWidgets.QLineEdit(self.frame)
        self.istaPathLine.setObjectName("istaPathLine")
        self.horizontalLayout.addWidget(self.istaPathLine)
        self.istaToolButton = QtWidgets.QToolButton(self.frame)
        self.istaToolButton.setObjectName("istaToolButton")
        self.horizontalLayout.addWidget(self.istaToolButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rcmddLabel = QtWidgets.QLabel(self.frame)
        self.rcmddLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rcmddLabel.setObjectName("rcmddLabel")
        self.verticalLayout_2.addWidget(self.rcmddLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rcmddPathLine = QtWidgets.QLineEdit(self.frame)
        self.rcmddPathLine.setObjectName("rcmddPathLine")
        self.horizontalLayout_2.addWidget(self.rcmddPathLine)
        self.rcmddToolButton = QtWidgets.QToolButton(self.frame)
        self.rcmddToolButton.setObjectName("rcmddToolButton")
        self.horizontalLayout_2.addWidget(self.rcmddToolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 39))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)
        self.actionProgram = QtWidgets.QAction(SettingsWindow)
        self.actionProgram.setObjectName("actionProgram")
        self.actionHome = QtWidgets.QAction(SettingsWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionSetting = QtWidgets.QAction(SettingsWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionInstructions = QtWidgets.QAction(SettingsWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.menuMenu.addAction(self.actionHome)
        self.menuMenu.addAction(self.actionInstructions)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        SettingsWindow.setWindowTitle(QtWidgets.QApplication.translate("SettingsWindow", "Settings", None, -1))
        self.settingsLabel.setText(QtWidgets.QApplication.translate("SettingsWindow", "Settings", None, -1))
        self.saveSettingsButton.setText(QtWidgets.QApplication.translate("SettingsWindow", "Save", None, -1))
        self.istaLabel.setText(QtWidgets.QApplication.translate("SettingsWindow", "ISTA-Net Models Directory", None, -1))
        self.istaToolButton.setText(QtWidgets.QApplication.translate("SettingsWindow", "...", None, -1))
        self.rcmddLabel.setText(QtWidgets.QApplication.translate("SettingsWindow", "RCMDD Models Directory", None, -1))
        self.rcmddToolButton.setText(QtWidgets.QApplication.translate("SettingsWindow", "...", None, -1))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("SettingsWindow", "Menu", None, -1))
        self.actionProgram.setText(QtWidgets.QApplication.translate("SettingsWindow", "Program", None, -1))
        self.actionHome.setText(QtWidgets.QApplication.translate("SettingsWindow", "Home", None, -1))
        self.actionSetting.setText(QtWidgets.QApplication.translate("SettingsWindow", "Setting", None, -1))
        self.actionInstructions.setText(QtWidgets.QApplication.translate("SettingsWindow", "Instructions", None, -1))

